name: input_sheet
description: A flutter package to help apps with extensive forms, implementing inputs as BottomSheet to make it enjoyable.
version: 0.2.1
homepage: https://github.com/Ibraheemcodersme/input-sheet.git

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^1.2.1
  uuid: ^3.0.7
  intl: ^0.17.0
  quiver: ^3.0.0
  camera: ^0.8.0
  flutter_mobx: ^1.1.0
  path_provider: ^2.0.11
  keyboard_utils: ^1.2.1
  after_layout: ^1.0.7+2
  video_compress: ^2.0.0
  video_player: ^0.10.11
  flutter_masked_text: ^0.8.0
  permission_handler: ^10.2.0
  flutter_feather_icons: ^1.0.3
  cached_network_image: ^2.2.0+1
  flutter_keyboard_size: ^0.1.2+2
  flutter_cupertino_date_picker: ^1.0.24

dev_dependencies:
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
